# Generated by Django 3.1 on 2020-08-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_tucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=1000, null=True)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '吐槽信息',
                'verbose_name_plural': '吐槽信息',
            },
        ),
    ]
