# Generated by Django 3.1 on 2020-08-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_db_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_apis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True, verbose_name='项目id')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='接口名字')),
                ('api_method', models.CharField(max_length=10, null=True, verbose_name='请求方式')),
                ('api_url', models.CharField(max_length=1000, null=True, verbose_name='url')),
                ('api_header', models.CharField(max_length=1000, null=True, verbose_name='请求头')),
                ('api_login', models.CharField(max_length=10, null=True, verbose_name='是否带登陆态')),
                ('api_host', models.CharField(max_length=100, null=True, verbose_name='域名')),
                ('des', models.CharField(max_length=100, null=True, verbose_name='描述')),
                ('body_method', models.CharField(max_length=20, null=True, verbose_name='请求体编码格式')),
                ('api_body', models.CharField(max_length=1000, null=True, verbose_name='请求体')),
                ('result', models.TextField(null=True, verbose_name='返回体')),
                ('sign', models.CharField(max_length=10, null=True, verbose_name='是否验签')),
                ('file_key', models.CharField(max_length=50, null=True, verbose_name='文件key')),
                ('file_name', models.CharField(max_length=50, null=True, verbose_name='文件名')),
                ('public_header', models.CharField(max_length=1000, null=True, verbose_name='全局变量-请求头')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
            },
        ),
    ]
